export const ACTIONS = {
    ASSETS_POST_DATA_REQUEST: 'ASSETS_POST_DATA_REQUEST',
    ASSETS_STORE_PAYLOAD_REQUEST: 'ASSETS_STORE_PAYLOAD_REQUEST',
    ASSETS_POST_DATA_FAILED: 'ASSETS_POST_DATA_FAILED',
    ASSETS_POST_DATA_SUCCEED: 'ASSETS_POST_DATA_SUCCEED',
    ASSETS_POPULATE_CALCULATED_RESULTS: 'ASSETS_POPULATE_CALCULATED_RESULTS',
    ASSETS_REFRESH: 'ASSETS_REFRESH',
    CLEAR_ALL_DATA_ASSETS: 'CLEAR_ALL_DATA_ASSETS',

    WAITING_SCREEN_SHOW: 'WAITING_SCREEN_SHOW',
    WAITING_SCREEN_HIDE: 'WAITING_SCREEN_HIDE',
}